# SPDX-License-Identifier: Apache-2.0
# Copyright (C) 2025, The Spine Docs organization and its contributors.

- id: check-headers
  name: Check SPDX headers
  description: Check and optionally fix SPDX license headers in Python files
  entry: check-headers/check-headers.py
  language: python
  files: '^(src|test)/.*\.py$'
  pass_filenames: true

- id: check-dco
  name: Check DCO sign-off
  description: Check that commit message has DCO sign-off
  entry: dco/check-dco.py
  language: python
  stages: [commit-msg]
