# SPDX-License-Identifier: Apache-2.0
# Copyright (C) 2025, The Spine Docs organization and its contributors.

name: 'DCO Check'
description: 'Check that all commits in a PR have DCO sign-off'
author: 'The Spine Docs organization'

runs:
  using: 'composite'
  steps:
    - name: Check DCO sign-off on all commits
      shell: bash
      run: |
        # Get all commits in the PR
        if [ "${{ github.event_name }}" = "pull_request" ]; then
          COMMITS=$(git log origin/${{ github.base_ref }}..${{ github.sha }} --format="%H")
        else
          # For push events, check only the current commit
          COMMITS="${{ github.sha }}"
        fi

        MISSING_DCO=false

        for commit in $COMMITS; do
          MESSAGE=$(git log -1 --format=%B $commit)
          if ! echo "$MESSAGE" | grep -q "^Signed-off-by:"; then
            echo "❌ Commit $commit is missing DCO sign-off"
            echo "   Commit message:"
            echo "$MESSAGE" | head -5
            echo ""
            MISSING_DCO=true
          fi
        done

        if [ "$MISSING_DCO" = true ]; then
          echo ""
          echo "Error: One or more commits are missing DCO sign-off!"
          echo "Please sign your commits with: git commit -s"
          echo ""
          echo "To fix existing commits:"
          echo "  git rebase --signoff origin/${{ github.base_ref }}"
          exit 1
        fi

        echo "✅ All commits have DCO sign-off"

branding:
  icon: 'check-circle'
  color: 'green'
