# SPDX-License-Identifier: Apache-2.0
# Copyright (C) 2025, The Spine Docs organization and its contributors.

name: 'Sync Labels'
description: 'Sync GitHub labels from source repository to downstream repositories listed in repos.yaml'
author: 'The Spine Docs organization'

runs:
  using: 'composite'
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install PyGithub PyYAML

    - name: Sync labels to downstream repos
      shell: bash
      env:
        GITHUB_TOKEN: ${{ github.token }}
      run: |
        python ${{ github.action_path }}/../spine_cicd_actions/sync_labels.py

branding:
  icon: 'tag'
  color: 'blue'
